name: Back test aws

on:
  push:
    branches:
      - main

  deploy:
    runs-on: aws-back
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Moving and executing project
        run: cd back-test && git pull
