name: Back test aws

on:
  push:
    branches:
      - main

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: aws-back
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete project
        run: rm -rf back-test
      - name: clone repository
        run: git clone https://github.com/AGuekdjian/back-test.git
      - name: Moving and executing project
        run: cd back-test && nohup mvn spring-boot:run &
